##

POST https://csc322cer6functions.azurewebsites.net/api/add?code=WaBaCGfSQTLlT6TyFMdutTTem0z4ZLkTnrhbDBBxwnT4k5V3bK77Mg== HTTP/1.1
content-type: application/json

{
    "num1": 5,
    "num2": 2
}

###